/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ihm;

/**
 *
 * @author GRL4714A
 */
public class Calculateur extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculateur.class.getName());

    /**
     * Creates new form Calculateur
     */
    public Calculateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_temperature = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_vitesseVent = new javax.swing.JTextField();
        jButton_calculer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_res = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Température (°C)");

        jTextField_temperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_temperatureMouseClicked(evt);
            }
        });
        jTextField_temperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_temperatureActionPerformed(evt);
            }
        });

        jLabel2.setText("et vitesse du vent (km/h)");

        jTextField_vitesseVent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_vitesseVentMouseClicked(evt);
            }
        });
        jTextField_vitesseVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_vitesseVentActionPerformed(evt);
            }
        });

        jButton_calculer.setText("Calculer");
        jButton_calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculerActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>Indice de refroidissement éolien<br/>(température ressentie (°C))</html>");

        jTextField_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_resActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_res, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_vitesseVent, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_calculer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_vitesseVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_calculer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_res, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int temperature;
    int vitesseVent;
    int resultat;
    
    private int calculIRE(int temperature, int vitesseVent) {
        double result = 13.12 + 0.62215 * temperature +
                (0.3965 * temperature - 11.37) * Math.pow(vitesseVent, 0.16);
        return (int) result;
    }
    
    private void jTextField_temperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_temperatureActionPerformed
        try {
            temperature = Integer.parseInt(jTextField_temperature.getText());
        } catch (NumberFormatException e){
            temperature = 0;
            jTextField_temperature.setText("0");
        }
        if(temperature < -50){
            temperature = -50;
            jTextField_temperature.setText("-50");
        }
        if(temperature > 10){
            temperature = 10;
            jTextField_temperature.setText("10");
        }
        
        jTextField_temperature.setText(""+temperature);
        jTextField_vitesseVent.setEnabled(true);
        jButton_calculer.setEnabled(true);
    }//GEN-LAST:event_jTextField_temperatureActionPerformed

    private void jButton_calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculerActionPerformed
        resultat = calculIRE(temperature, vitesseVent);
        jTextField_res.setText(""+resultat);
    }//GEN-LAST:event_jButton_calculerActionPerformed

    private void jTextField_vitesseVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_vitesseVentActionPerformed
        try {
            vitesseVent = Integer.parseInt(jTextField_temperature.getText());
        } catch (NumberFormatException e){
            vitesseVent = 0;
            jTextField_vitesseVent.setText("0");
        }
        if(vitesseVent != 0 && vitesseVent < 57){
            vitesseVent = 5;
            jTextField_vitesseVent.setText("5");
        }
        if(vitesseVent > 175){
            vitesseVent = 175;
            jTextField_vitesseVent.setText("175");
        }
        
        jTextField_vitesseVent.setText(""+vitesseVent);
        jTextField_temperature.setEnabled(true);
        jButton_calculer.setEnabled(true);
    }//GEN-LAST:event_jTextField_vitesseVentActionPerformed

    private void jTextField_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_resActionPerformed
        
    }//GEN-LAST:event_jTextField_resActionPerformed

    private void jTextField_temperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_temperatureMouseClicked
        jTextField_temperature.setEnabled(true);
        jTextField_vitesseVent.setEnabled(false);
        jTextField_res.setEnabled(false);
        jButton_calculer.setEnabled(false);
        jTextField_res.setText("");
    }//GEN-LAST:event_jTextField_temperatureMouseClicked

    private void jTextField_vitesseVentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_vitesseVentMouseClicked
        jTextField_vitesseVent.setEnabled(true);
        jTextField_temperature.setEnabled(false);
        jTextField_res.setEnabled(false);
        jButton_calculer.setEnabled(false);
        jTextField_res.setText("");
    }//GEN-LAST:event_jTextField_vitesseVentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculateur().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calculer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField_res;
    private javax.swing.JTextField jTextField_temperature;
    private javax.swing.JTextField jTextField_vitesseVent;
    // End of variables declaration//GEN-END:variables
}
